// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GoogleCallbackAccountsGoogleLoginCallbackGetData, GoogleCallbackAccountsGoogleLoginCallbackGetResponses, GoogleLoginAccountsGoogleLoginGetData, GoogleLoginAccountsGoogleLoginGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, HelloApiHelloGetData, HelloApiHelloGetResponses, LogoutApiLogoutPostData, LogoutApiLogoutPostResponses, MeApiMeGetData, MeApiMeGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Google Login
 *
 * Redirect the browser to Google's consent screen.
 */
export const googleLoginAccountsGoogleLoginGet = <ThrowOnError extends boolean = false>(options?: Options<GoogleLoginAccountsGoogleLoginGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GoogleLoginAccountsGoogleLoginGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/accounts/google/login',
        ...options
    });
};

/**
 * Google Callback
 *
 * Handle the Google OAuth callback.
 *
 * Exchange the authorization code for tokens, fetch the user profile,
 * create a JWT, set it as an httpOnly cookie, and redirect to the frontend.
 */
export const googleCallbackAccountsGoogleLoginCallbackGet = <ThrowOnError extends boolean = false>(options?: Options<GoogleCallbackAccountsGoogleLoginCallbackGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GoogleCallbackAccountsGoogleLoginCallbackGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/accounts/google/login/callback',
        ...options
    });
};

/**
 * Hello
 */
export const helloApiHelloGet = <ThrowOnError extends boolean = false>(options?: Options<HelloApiHelloGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HelloApiHelloGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/hello',
        ...options
    });
};

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/health',
        ...options
    });
};

/**
 * Me
 *
 * Return the authenticated user's profile from the JWT cookie.
 */
export const meApiMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<MeApiMeGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/me',
        ...options
    });
};

/**
 * Logout
 *
 * Clear the authentication cookie.
 */
export const logoutApiLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutApiLogoutPostResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/logout',
        ...options
    });
};
