// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * DetailResponse
 */
export type DetailResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UserProfile
 */
export type UserProfile = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Picture
     */
    picture: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
};

export type GoogleLoginAccountsGoogleLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts/google/login';
};

export type GoogleLoginAccountsGoogleLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GoogleCallbackAccountsGoogleLoginCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts/google/login/callback';
};

export type GoogleCallbackAccountsGoogleLoginCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HelloApiHelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type HelloApiHelloGetResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type HelloApiHelloGetResponse = HelloApiHelloGetResponses[keyof HelloApiHelloGetResponses];

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type MeApiMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeApiMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type MeApiMeGetResponse = MeApiMeGetResponses[keyof MeApiMeGetResponses];

export type LogoutApiLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type LogoutApiLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: DetailResponse;
};

export type LogoutApiLogoutPostResponse = LogoutApiLogoutPostResponses[keyof LogoutApiLogoutPostResponses];
